buildstable:
  stage: build
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_BASE: https://gitlab-ci-token:${CI_JOB_TOKEN}@gl.zz.de
  script:
    - apt-get update && apt-get -fuy install git
    - git clone ${GIT_BASE}/mirror/libosmium && git -C libosmium checkout -b build 1bb69ec6233b2d065196100b27b9655529d9ad5a
    - git clone ${GIT_BASE}/mirror/protozero && git -C protozero checkout -b build 5ffe45b718ad14b28a0a7b4044d60fcc0ddba012
    - apt-get update
    - apt-get install -fuy build-essential cmake cmake-data libboost-all-dev libgdal-dev libbz2-dev libexpat1-dev libsparsehash-dev
    - mkdir build
    - ( cd build ; cmake .. )
    - make -C build

buildlatestdep:
  stage: build
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_BASE: https://gitlab-ci-token:${CI_JOB_TOKEN}@gl.zz.de
  script:
    - apt-get update && apt-get -fuy install git
    - git clone ${GIT_BASE}/mirror/libosmium
    - git clone ${GIT_BASE}/mirror/protozero
    - apt-get update
    - apt-get install -fuy build-essential cmake cmake-data libboost-all-dev libgdal-dev libbz2-dev libexpat1-dev libsparsehash-dev
    - mkdir build
    - ( cd build ; cmake .. )
    - make -C build

buildbookworm:
  stage: build
  image: amd64/debian:bookworm
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_BASE: https://gitlab-ci-token:${CI_JOB_TOKEN}@gl.zz.de
  script:
    - apt-get update && apt-get -fuy install git
    - git clone ${GIT_BASE}/mirror/libosmium && git -C libosmium checkout -b build 1bb69ec6233b2d065196100b27b9655529d9ad5a
    - git clone ${GIT_BASE}/mirror/protozero && git -C protozero checkout -b build 5ffe45b718ad14b28a0a7b4044d60fcc0ddba012
    - apt-get update
    - apt-get install -fuy build-essential cmake cmake-data libboost-all-dev libgdal-dev libbz2-dev libexpat1-dev libsparsehash-dev
    - mkdir build
    - ( cd build ; cmake .. )
    - make -C build
  artifacts:
    paths:
      - build/wayproblems
    expire_in: 3 weeks

