language: cpp
compiler: gcc
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - libboost1.55-all-dev
      - libboost-program-options1.55-dev
      - libgdal-dev
      - libbz2-dev
      - libexpat1-dev
      - libsparsehash-dev
      - libgeos++-dev
      - libproj-dev

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - git submodule update --init
    - gcc -v && g++ -v && cmake --version
    - cmake -LA ..

script:
    - make VERBOSE=1

