language: cpp
compiler: gcc
sudo: false
dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - build-essential
            - cmake-data
            - cmake
            - libboost-all-dev
            - libgdal-dev
            - libbz2-dev
            - libexpat1-dev
            - libsparsehash-dev
            - libgeos++-dev
            - libproj-dev

before_script:
    - git submodule update --init
    - gcc -v && g++ -v && cmake --version
    - cmake -LA .

script:
    - make VERBOSE=1

