language: cpp
compiler: gcc
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake-data
            - cmake
            - libboost1.55-all-dev
            - libboost-program-options1.55-dev
            - libgdal-dev
            - libbz2-dev
            - libexpat1-dev
            - libsparsehash-dev
            - libgeos++-dev
            - libproj-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_script:
    - git submodule update --init
    - gcc -v && g++ -v && cmake --version
    - cd ${TRAVIS_BUILD_DIR}
    - cmake -LA ..

script:
    - make VERBOSE=1

